#!/bin/sh
xrandr --output VIRTUAL1 --off --output eDP1 --mode 1920x1080 --pos 3120x0 --rotate normal --output DP1 --mode 1920x1200 --pos 1200x0 --rotate normal --output HDMI2 --off --output HDMI1 --off --output DP2 --mode 1920x1200 --pos 0x0 --rotate left
xrandr --output VIRTUAL1 --off --output eDP1 --mode 1920x1080 --pos 3120x0 --rotate normal --output DP1 --mode 1920x1200 --pos 1200x0 --rotate normal --primary --output HDMI2 --off --output HDMI1 --off --output DP2 --mode 1920x1200 --pos 0x0 --rotate left
