#!/bin/sh
sudo sysctl -w net.ipv4.ip_forward=1
sudo iptables -F
sudo iptables --table nat --append POSTROUTING --out-interface eth0 -j MASQUERADE -m comment --comment 'masq wlan0 outgoing'
sudo iptables --append FORWARD --in-interface wlan0 -j ACCEPT -m comment --comment 'allow eth0 incoming'


